/*
    Array é um forma de guardar multiplos dados em apenas uma variável...
    As arrays podem ter qualquer tipo de dado...
    As arrays não possuem tamanho fixo, ou seja elas podem ser alteradas durante a execução do programa...
*/

const pessoas = ['Matheus', 'Rafael', 'Gabriel', 'Pedro'];
console.log(pessoas);

// Desempacotando uma array...
console.log('Integrantes da família')
for (pessoa in pessoas){
    console.log(`Integrande ${Number(pessoa) + 1}: ${pessoas[pessoa]}`);
}

// Quando procuramos por um valor que não existe dentro de uma array, ela ira nos retornar Undefined
console.log(pessoas[4]); // O indice 4 não existe...

console.log(pessoas.length); // length retorna quantos elementos temos dentro de nossa array...
pessoas.push('Papa'); // Podemos usar o push para adicionar elementos em uma array...
console.log(pessoas);

console.log(pessoas.pop()); // Retorna o último valor de uma array...

delete pessoas[4]; // Ele vai tirar o elemento de indice 4 da nossa array...
console.log(pessoas);

// Uma array é do tipo object...