// Booleano é nada mais nada menos do que tue or false...

let isAtivo = true;
console.log(isAtivo);

isAtivo = false;
console.log(isAtivo);

// Podemos usar valores númericos para retornar um bool...
isAtivo = 1;
console.log(!!isAtivo); // ! -> Siginifica negação, logo se colocarmos somente uma ! ele ira retornar o contrario de isAtivo...
// com !! ele retorna o o valor de isAtivo...
// Colocando a negação na frente meio que forçamos ele retornar verdadeiro ou falso...

// Valores que sempre irão retornar true...
console.log(!!3); // Qualquer número que não seja 0...
console.log(!!-1);
console.log(!!' '); // Strings que não estejam vazias...
console.log(!!'Texto');
console.log(!![]); // Arrays vazias...
console.log(!!{}); // Objetos...
console.log(!!Infinity); // Infinito ou qualquer numero dividido por 0...

// Valores que sempre irão retornar false...
console.log(!!0); // 0 sempre será falso...
console.log(!!''); // Strings Vazias... 
console.log(!!null); // O valor nulo sempre será falso...
console.log(!!NaN); // Not a Number sempre será falso...
console.log(!!undefined); // Undefined sempre será falso...

// Em operações lógicas...
const nome = '';
console.log(nome || 'Desconhecido'); // Se nome for falso ele irá mostrar desconhecido, mas se o nome for verdadeiro
// Ele irá mostrar o nome...