/*
    Comentários são textos usados para explicar o seu código, eles são ignorados quando o código for rodar...
*/

// -> Comentário de uma só linha...
/*
    -> Comentário que poder ter várias linhas...
*/

// Os comentários são muito importantes em um programa, torna ele mais legivel
// Sendo assim um código bom é a quele bem comentado...