/*
    Funções são muito importantes no JS...
*/
// As funções estão em tudo praticamente...
console.log(typeof Object); // O objeto é uma função em JS...
class produto {}
console.log(typeof produto); // Classes também são funções dentro do JS...


