// Em JS conseguimos içar uma variável mover uma variável sempre para o topo do programa...
// Em algumas linguagens isso daria um erro pois o programa começa a ler de cima pra baixo...

console.log(a); // Undefined porque não sabe qual o valor da variavel a...
var a = 2;
console.log(a); // 2

// Nunca faça isso é apenas uma curiosidade...
// Sempre comece declarando suas variáveis!!!!!