// Alguns cuidados...


// Quando dividimos um número por 0 o JS retorna o infinito...
// Quanto mais 0 dps da virgula tiver um número, maior será o resultado na divisão...
console.log(7 / 0);

// Como a tipagem do JS é fraca podemos dividir uma str com um Number...
console.log('10' / 2);
// O JS consegue ver se o conteudo dentro da string pode ser um Number e faz a operação...

// Não é possivel repetir uma string multiplicando ela...
console.log('Show!' * 5); // -> NaN = Not a Number...

// Resultados menos precisos com floats...
console.log(0.1 + 0.7); // -> 0.799999999999...

// .ToFixed
console.log((10).toFixed(2)); 