// Tipos Numéricos...

// O tipo Number serve tanto para inteiros quanto para floats...

const peso1 = 1.0;
const peso2 = Number('2.0'); // Podemos tranformar a str '2.0' em um number utilizando a função Number...

console.log(Number.isInteger(peso1)); // Podemos verificar se um número é inteiro utilizando esse método...
// Ele logo retorna true, mesmo que seja 1.0 pois ele entende que .0 seja o numero inteiro...

const avaliacao1 = 8.789;
const avaliacao2 = 7.789;

const total = (peso1 * avaliacao1) + (peso2 * avaliacao2);
const media = total / (peso1 + peso2);

console.log(media.toFixed(2)); // Podemos reduzir o numero de casas decimais exibidas usando o seguinte método...
console.log(media.toString(2)); // Podemos transformar o nosso Number em uma string e também transforma-lo em binário...