// Objetos são representados por {}...
// Um objeto é uma coleção de chave e valor por ex: Nome: Matheus
// Nome é a chave e Matheus é o valor...

const pessoa1 = {}; // -> Criamos nosso objeto...
pessoa1.nome = 'Matheus'; // -> Lhe atribuimos a key nome e o value Matheus...
pessoa1.idade = 19;
console.log(pessoa1);

// Seriam como os dicionários do python...