/*
    Strings são textos...
    Em JS podemos colocar strings de 3 formas: '', "" e ``
*/

const escola = 'Escola';

console.log(escola.charAt(2)); // A função charAt(indice) retorna a letra de determinado indice...

console.log(escola.charCodeAt(3)); // Me retorna o valor na tabela unicode...

console.log(escola.indexOf('l')); // Me retorna o índice da letra...

// Podemos fatiar strings usando a função substring...
console.log(escola.substring(0, 3));

// Podemos concatenar strings usando a função concat...
console.log('Nome: '.concat(escola).concat('!'));

console.log(escola.replace(3, '0')); // Ele ira trocar o nosso indice 3 por 0...