/*
    Template strings é uma forma de formatar as strings sem ter que concatenar elas...
*/

const nome = 'Matheus';
console.log(`Olá, ${nome}!`); // Em templateStrings usamos o crase e chaves para colocar os dados dentro do texto...

// Seria como uma f'' do python... tem a mesma utilidade...