/*
    Tipagem é definir se um dado é um inteiro, str, float ou bool...
    No JS a tipagem é dinâmica, ou seja, não é preciso tipar os dados...
*/

let qualquer = 'Olá';
console.log(typeof qualquer); // Vamos ver qual a tipagem de qualquer...
// Logo vemos que o tipo é string -> TEXTO...

// A mesma variável pode ter multiplos valores...