// Loop de repetição for...
// for (variavel; condição; incremento)
for (var i = 0; i < 10; i++){
    console.log(i); // Ele irá imprimir todos os valores até 9
    // Quando i = 10 é falso e para o loop´de repetição...
}

console.log(`i = ${i}`); // Ele vai imprimir 10 pois o loop parou no 10...

// Veja que mesmo fora do loop a variavel i ainda funciona, isso porque usamos o var...