// Uma variável é declarada com var logo em seguida seu nome...
var numero = 3; // Criamos uma variável chamada numero que recebe o valor 3...
// Ou seja dentro dessa variável amarzenamos o valor 3...

// Também podemos usar let para declarar uma variável, existe diferença entre let e var mas isso ficará mais pra frente do curso...
let letra = 'A';

// Uma constante é declaraca com const e o seu valor não pode ser alterado, ele deve se manter o mesmo até o fim do programa...
const peca = 2;